sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build images
# docker build -t eyilmaz/rcswitch-pi-homebridge ./homebridge
- docker build -t eyilmaz/rcswitch-pi-switch ./switch
# push image
- >
  if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push eyilmaz/rcswitch-pi-switch
  fi
