
version: "2.1"

services:

  switch:
    hostname: switch
    privileged: true
    image: eyilmaz/rcswitch-pi-switch
    ports:
      - ${IP_ADDR}:9876:9876
    labels:
      - rcswitch.pi.stack=switch
      - rcswitch.pi.user=root privileged
    environment:
      - RC_SWITCH_OUTPUT_PIN=3
