
version: "2.1"

volumes:
  homebridge_config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/homebridge/config
      o: bind
  dbus:
    driver: local
    driver_opts:
      type: none
      device: /var/run/dbus
      o: bind

services:

  switch:
    hostname: switch
    privileged: true
    build:
      context: ./switch/
    labels:
      - rcswitch.pi.stack=switch
      - rcswitch.pi.user=root privileged
    environment:
      - RC_SWITCH_OUTPUT_PIN=3

  homebridge:
    hostname: homebridge
    build:
      context: ./homebridge/
    ports:
      - ${IP_ADDR}:51826:51826
    labels:
      - rcswitch.pi.stack=homebridge
      - rcswitch.pi.user=non-root non-privileged homebridge
    volumes:
      - homebridge_config:/home/homebridge/.homebridge
      - dbus:/var/run/dbus